export const APPLICATION_TABLE_HEADERS = [
  'id',
  'created_at',
  'fullName',
  'preferredFullName',
  'phoneticPronunciation',
  'nickname',
  'nuid',
  'pronouns',
  'email',
  'phoneNumber',
  'year',
  'college',
  'major',
  'minors',
  'constituency',
  '\n',
];

export const NOMINATION_TABLE_HEADERS = [
  'id',
  'created_at',
  'fullName',
  'email',
  'nominee',
  'constituency',
  'college',
  'major',
  'graduationYear',
  'recieveSenatorInfo',
  'status',
  '\n',
];
